/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Adult from "../public/adult.png";
import AdultRound from "../public/adult1.png";
import Child from "../public/child.png";
import Pozvonok from "../public/pozvonok.png";
import Tired from "../public/tired.png";
import Hands from "../public/hands.png";
import Bedro from "../public/bedro.png";
import Glot from "../public/glotka.png";
import Sust from "../public/sust.png";
import Lung from "../public/lung.png";
import Run from "../public/run.png";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  function pozvonok_on () {
    (document.querySelector(".Home_pozvonok_text__JtcpI")as HTMLElement).style.display = "block";
  }

  function pozvonok_off () {
    (document.querySelector(".Home_pozvonok_text__JtcpI")as HTMLElement).style.display = "none";
  }

  function hands_on () {
    (document.querySelector(".Home_hands_text__WrzaR")as HTMLElement).style.display = "block";
  }

  function hands_off () {
    (document.querySelector(".Home_hands_text__WrzaR")as HTMLElement).style.display = "none";
  }

  function tired_on () {
    (document.querySelector(".Home_tired_text__voEPA")as HTMLElement).style.display = "block";
  }

  function tired_off () {
    (document.querySelector(".Home_tired_text__voEPA")as HTMLElement).style.display = "none";
  }

  function glot_on () {
    (document.querySelector(".Home_glot_text__RDuJf")as HTMLElement).style.display = "block";
  }

  function glot_off () {
    (document.querySelector(".Home_glot_text__RDuJf")as HTMLElement).style.display = "none";
  }

  function lung_on () {
    (document.querySelector(".Home_lung_text__biPKB")as HTMLElement).style.display = "block";
  }

  function lung_off () {
    (document.querySelector(".Home_lung_text__biPKB")as HTMLElement).style.display = "none";
  }

  function bedro_on () {
    (document.querySelector(".Home_bedro_text__1hNfB")as HTMLElement).style.display = "block";
  }

  function bedro_off () {
    (document.querySelector(".Home_bedro_text__1hNfB")as HTMLElement).style.display = "none";
  }

  function sust_on () {
    (document.querySelector(".Home_sust_text__uWRVY")as HTMLElement).style.display = "block";
  }

  function sust_off () {
    (document.querySelector(".Home_sust_text__uWRVY")as HTMLElement).style.display = "none";
  }

  function run_on () {
    (document.querySelector(".Home_run_text___jcxV")as HTMLElement).style.display = "block";
  }

  function run_off () {
    (document.querySelector(".Home_run_text___jcxV")as HTMLElement).style.display = "none";
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>А вдруг СМА?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.main_container}>
          <h1 className={styles.document_title}>А вдруг СМА?</h1>
          <h2 className={styles.document_subtitle}>
            Выберите, кто ваш пациент:
          </h2>
          <div className={styles.picture_container}>
            <div className={styles.sex_container}>
              <p className={styles.picture_header}>Взрослый</p>
              <Image alt={"adult"} src={Adult} className={styles.pic} />
              <div className={styles.text_container}>
                <p className={styles.disease_text}>
                  Менее тяжелые формы СМА могут возникать и диагностироваться в
                  зрелом возрасте.
                </p>
                <p className={styles.disease_text}>
                  По сравнению с СМА у детей, СМА у взрослых может иметь более
                  легкие симптомы, но без патогенетической терапии пациенты со
                  СМА 2-3 типа неуклонно теряют двигательные навыки.
                </p>
                <p className={styles.disease_text}>
                  По сравнению с СМА в детстве, течение СМА у взрослых может
                  быть более коварным и трудным для распознавания.
                </p>
              </div>
            </div>
            <div className={styles.sex_container}>
              <p className={styles.picture_header}>Ребенок</p>
              <Image alt={"child"} src={Child} className={styles.pic} />
              <div className={styles.text_container}>
                <p className={styles.disease_text}>
                  Ребенок, плохо удерживающий голову, когда ему придают сидячее
                  положение, с вялыми движениями нижних конечностей или с трудом
                  тянущийся к предметам, но при этом с осмысленным и ярким
                  взглядом, улыбающийся и социально активный, вызывает
                  настороженность в отношении наличия СМА.
                </p>
                <p className={styles.disease_text}>
                  Младенцам со СМА необходимо экстренное направление к
                  специалисту, ранняя диагностика и обеспечение терапией,
                  спасающей жизнь, поскольку эти мотонейроны очень быстро
                  подвергаются дегенерации при прогрессировании заболевания
                </p>
              </div>
            </div>
          </div>
          <p className={styles.report_text}>
            Сообщает ли один из ваших пациентов о следующих симптомах?{" "}
            <a className={styles.report_link}>
              (нажмите на любую иконку и узнайте больше)
            </a>
          </p>
          <div className={styles.var_container}>
            <p className={styles.pozvonok_text}>Сколиоз</p>
            <div className={styles.pozvonok_image} onMouseOver={pozvonok_on} onMouseLeave={pozvonok_off}>
              <Image
                alt={"pozvonok"}
                src={Pozvonok}
                className={styles.pozvonok_image}
              />
            </div>
            <p className={styles.tired_text}>Утомляемость</p>
            <div className={styles.tired_image} onMouseOver={tired_on} onMouseLeave={tired_off}>
              <Image alt={"tired"} src={Tired} className={styles.tired_image} />
            </div>
            <p className={styles.hands_text}>
              Ограниченная способность поднимать руки и переносить предметы
            </p>
            <div className={styles.hands_image}>
              <Image alt={"hands"} src={Hands} className={styles.hands_image} onMouseOver={hands_on} onMouseLeave={hands_off}/>
            </div>
            <div className={styles.adult_image}>
              <Image alt={"adult"} src={AdultRound} className={styles.adult_image} />
            </div>
            <p className={styles.bedro_text}>Вывих бедра</p>
            <div className={styles.bedro_image} onMouseOver={bedro_on} onMouseLeave={bedro_off}>
              <Image alt={"bedro"} src={Bedro} className={styles.bedro_image} />
            </div>
            <p className={styles.glot_text}>Нарушения жевания и глотания</p>
            <div className={styles.glot_image} onMouseOver={glot_on} onMouseLeave={glot_off}>
              <Image alt={"glot"} src={Glot} className={styles.glot_image} />
            </div>
            <p className={styles.sust_text}>Контрактура суставов</p>
            <div className={styles.sust_image} onMouseOver={sust_on} onMouseLeave={sust_off}>
              <Image alt={"sust"} src={Sust} className={styles.sust_image} />
            </div>
            <p className={styles.lung_text}>Дыхательная недостаточность/ респираторная дисфункция</p>
            <div className={styles.lung_image} onMouseOver={lung_on} onMouseLeave={lung_off}>
              <Image alt={"lung"} src={Lung} className={styles.lung_image} />
            </div>
            <p className={styles.run_text}>Неспособность бегать, изменение походки</p>
            <div className={styles.run_image} onMouseOver={run_on} onMouseLeave={run_off}>
              <Image alt={"run"} src={Run} className={styles.run_image} />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
